@version: 3.38
@include "scl.conf"

options {
    chain_hostnames(no);
    use_dns(no);
    keep_hostname(yes);
    create_dirs(yes);
    owner("root");
    group("root");
    perm(0640);
    dir_perm(0750);
    stats_freq(0);
};

source s_net {
    udp(ip("0.0.0.0") port(514));
    tcp(ip("0.0.0.0") port(514));
};

source s_local {
    internal();
};

destination d_pfsense {
    file("/var/log/syslog-ng/pfsense.log"
        template("$ISODATE $HOST $PROGRAM[$PID]: $MSGONLY\n")
        template_escape(no));
};

destination d_local {
    file("/var/log/syslog-ng/local.log"
        template("$ISODATE $HOST $PROGRAM[$PID]: $MSGONLY\n")
        template_escape(no));
};

log {
    source(s_net);
    destination(d_pfsense);
};

log {
    source(s_local);
    destination(d_local);
};
